### ISSUE TITLE
No Player / No Listener hostname found in Docker environment

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hklages/node-red-contrib-sonos-events#1]
I love the concept of your enhance Sonos Node but have not yet been able to get it running in my Docker environment.

I have opened the port 6329 in the docker environment but still not able to receive any feedback from Sonos

1) The Sonos-Plus node is working fine
2) The Sonos-Event node is not able to detect the Sonos players
3) No Listener-Hostname can be found 
![image](https://user-images.githubusercontent.com/2195190/105680272-95774000-5f43-11eb-9dfe-f74aecaa6dd8.png)

4) I have entered the correct IP-Adress manually (192.168.2.226) => This IP is received by Sonos-Plus "household.get.groups"
![image](https://user-images.githubusercontent.com/2195190/105680995-a1afcd00-5f44-11eb-9a10-1813aa2a0aa5.png)

5) No player is detected (I have entered same IP 192.168.2.226) ==> nothing found with "Search" function

6) I've tried to establish an HTTP listenener on
![image](https://user-images.githubusercontent.com/2195190/105682463-978ece00-5f46-11eb-9b95-cb77773d14c0.png)
but I'm receiving the below error msg
`Error: connect ECONNREFUSED 192.168.2.226:6329 : http://192.168.2.226:6329/status`

Any idea, why I'm not receiving any feedback/even in your node ?

thanks for your help
regards

**Comment by hklages** [comment]
Hi. 

SONOS player IP is: 192.168.2.226 - right? 
Node-RED is running on 172.17.0.3 in a docker container- right? 
What kind of servicer is it? raspberry pi, Synology? 
What Node-RED version ? 
sonos-plus and sonos-events are installed on that Node-RED version - right? 

Is there a gateway between both networks?

**Comment by xX-Nexus-Xx** [comment]
Hi,

I just figured out the difference in network 192 vs 172 and now trying to setup the (ubuntu) docker so that the 192 network is accessible from the container

I'm running latest Node-Red and Sonos-plus and Sonos-Events are installed on Node-red on the same node/instance.

I will get you an update when I have sorted the network settings!

I was just confused because the Sonos-Plus node does work and can control and get data from Sonos and the Sonos-Event node is getting nothing

**Comment by xX-Nexus-Xx** [comment]
Yes, it does work !!

1) I have configure the container in HOST mode (previously BRIDGE) and port 6329 is open
2) I can now search and detect the SONOS devices
![image](https://user-images.githubusercontent.com/2195190/105776531-dc554c00-5fbc-11eb-9023-b7f43aa90ac9.png)
3) For testing purposes I have added the [Sonos-Notify node](https://flows.nodered.org/node/node-red-contrib-sonos-notify)
4) I have created a simple test-flow
`[{"id":"325ea348.bac69c","type":"debug","z":"ab1694c1.d34988","name":"event","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":570,"y":280,"wires":[]},{"id":"af3bc471.fa3c68","type":"sonos-notify","z":"ab1694c1.d34988","name":"Sonos Notify","address":"192.168.2.220","port":"","more":false,"x":350,"y":340,"wires":[["75f56353.bf9bec"]]},{"id":"75f56353.bf9bec","type":"debug","z":"ab1694c1.d34988","name":"notify","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":570,"y":340,"wires":[]},{"id":"76f9f90.911aa08","type":"sonosevents-selection","z":"ab1694c1.d34988","name":"SonosEvent","confignode":"748134ed.a302cc","playerHostname":"192.168.2.220","events":[{"fullName":"RenderingControlService.volume"}],"outputs":1,"x":350,"y":280,"wires":[["325ea348.bac69c"]]},{"id":"15496377.e498fd","type":"sonosevents-selection","z":"ab1694c1.d34988","name":"SonosEvent","confignode":"748134ed.a302cc","playerHostname":"192.168.2.226","events":[{"fullName":"RenderingControlService.volume"}],"outputs":1,"x":350,"y":220,"wires":[["8ef58719.735288"]]},{"id":"8ef58719.735288","type":"debug","z":"ab1694c1.d34988","name":"event","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":570,"y":220,"wires":[]},{"id":"748134ed.a302cc","type":"sonosevents-config","name":"Sonos-Event","listenerHostname":"192.168.2.202","listenerPort":""}]`

5) I had to execute a full rebuild
6) I had to reboot several times (don't know why)
7) now the events are coming fine
