### ISSUE TITLE
node-red and sonos-events

### ISSUE THREAD

**Issue by jackc94** [hklages/node-red-contrib-sonos-events#12]
Firstly, thank you for such an awesome node along with Sonos Plus. I’ve built a Dashboard in node-red to display individual player status but when a player is grouped what is a neat way of pointing the current information to the coordinator AVTransport instead of the player as individual players don’t report anything? This is true for playback state (shows “playing” when connected to a group) and AVTransport track information.

**Comment by hklages** [comment]
Thanks. 
Yes, all non coordinators in a group shows no or wrong status. That's done by SONOS - I cannot change it. 

That's why I decided to create the group commands for play, stop, pause ... 
I

**Comment by hklages** [comment]
no response
