### ISSUE TITLE
Issue with RenderingControl mutestate function always returning "off" even when Sonos speaker is muted

### ISSUE THREAD

**Issue by dobdib** [hklages/node-red-contrib-sonos-events#15]
**Problem:**
The RenderingControl mutestate function of the Sonos API always returns the value "off" even when the Sonos speaker is muted.

**Steps to Reproduce:**

1. Mute a Sonos speaker using the Sonos app or any other method.
2. Query the Sonos API with the RenderingControl mutestate function.
3. Observe that the returned value is always "off".

**Expected Behavior:**
When the Sonos speaker is muted, the RenderingControl mutestate function should return the corresponding value, indicating that the speaker is muted : on / off

**Additional Information:**

This issue was observed with release 1.2.3.
Everything was fine with release 1.2.1.

**Comment by hklages** [comment]
Hi.
I will wirklich on in in Monday.

Best regards, Henning

**Comment by hklages** [comment]
Hi. I can reproduce the bug in 1.2.3 and also that it had worked in 1.2.1.

**Comment by hklages** [comment]
I opened an issue [here](https://github.com/svrooij/node-sonos-ts/issues/194)

**Comment by dobdib** [comment]
> I opened an issue [here](https://github.com/svrooij/node-sonos-ts/issues/194)

Thank you

**Comment by hklages** [comment]
Hi - please update to 1.2.4. 
Does it fix the issue?

**Comment by dobdib** [comment]
> Hi - please update to 1.2.4. Does it fix the issue?

Should i see the upgrade from the nodered palette ?

**Comment by hklages** [comment]
Yes, but sometimes  it takes  a few hours to see the update

**Comment by dobdib** [comment]
Still not available for me.
Is there a way to force the update ?

**Comment by hklages** [comment]
... sometimes it takes. In the library there is already the [new version](https://flows.nodered.org/node/node-red-contrib-sonos-events)

if you are familiar with npm you can go to the node-red user directory and do 
`npm outdated`

The new version should show up and then
`npm update node-red-contrib-sonos-events`

**Comment by dobdib** [comment]
It works! Thanks for the efficiency.
