### ISSUE TITLE
node-red-contrib-sonos-events suddenly stopped working

### ISSUE THREAD

**Issue by mcarame** [hklages/node-red-contrib-sonos-events#18]
Hi hklages, I know that since 2024-06-15 node-red-contrib-sonos-events in no longer be actively developed, but mayby my problem is easy to fix.

Since some days ago node-red-contrib-sonos-events suddenly stopped working, with apparently no data exit from the node.

My setup is a Raspberrypi 4 with Nodered Via docker:
- Nodered 3.0.2
- node-red-contrib-sonos-events 1.2.5
- node-red-contrib-sonos-plus 6.9.0

To try to debug the problem i setup two simple node like this, but no dada exit even when the Sonos speakers changes track.

`
[
    {
      "id": "9e6170d0e6013e78",
      "type": "sonosevents-selection",
      "z": "ba958332.7f0528",
      "name": "",
      "confignode": "031f3e01879e994d",
      "playerHostname": "192.168.2.90",
      "events": [
        {
          "fullName": "AVTransportService.basics"
        }
      ],
      "outputs": 1,
      "x": 3430,
      "y": 380,
      "wires": [
        [
          "45be12e02ce06c6f"
        ]
      ]
    },
    {
      "id": "45be12e02ce06c6f",
      "type": "debug",
      "z": "ba958332.7f0528",
      "name": "",
      "active": true,
      "tosidebar": true,
      "console": false,
      "tostatus": false,
      "complete": "payload",
      "targetType": "msg",
      "statusVal": "",
      "statusType": "auto",
      "x": 3630,
      "y": 380,
      "wires": []
    },
    {
      "id": "031f3e01879e994d",
      "type": "sonosevents-config",
      "name": "192.168.2.140",
      "listenerHostname": "192.168.2.140",
      "listenerPort": "",
      "portType": "num"
    }
  ]
`

Attached, the Nodered log file.
[nodered-error.log](https://github.com/user-attachments/files/17504065/nodered-error.log)

Thank you in advance for your help!

**Comment by hklages** [comment]
Hi - I could not find anything in your error log related to sonos event node. 
 
Could you try to update to a more recent node-red (4.xx) and node.js (20...) version.

I am on nodered 4.05, node.js 20.18 and it works fine.
Your version is 3.02 and nodejs 16. 16

**Comment by mcarame** [comment]
Hi hklages, after a couple of reboot and a Raspbian OS security update, the node it start working again.
Thank you for your time and support!

**Comment by hklages** [comment]
Thanks for the Feedback.
