### ISSUE TITLE
No output via AVTransport content on track changes

### ISSUE THREAD

**Issue by j-p-l** [hklages/node-red-contrib-sonos-events#2]
Hey there! 
The events node does not trigger any output via "AVTransport content:" on track changes for me. When I trigger the "group.get.trackplus" on the universal node the output is correct. Does anyone have the same behavior?

**Comment by hklages** [comment]
Hi. Are your player grouped? Did you subscibe to the coordinator in that group.
In Import, Examples, node-red-contrib-events there is an example show_title - does that work for you?

**Comment by j-p-l** [comment]
Yes, my players are grouped. The example is great but only works if the player is the coordinator, which is not always the case. Is there any other way to define the player in the event node and output the "AVTransport content" of its coordinator?

**Comment by hklages** [comment]
I could not find any smart algorithm to handle that - so right now it is not possible. 
We can use Node-RED to find a work around. 

What other states do you have - what player should provide in what case the AVTransport data?
State 1: players are grouped and player1 is coordinator and provides AVTransport data

State2: player1 is not anymore coordinator and ????
- has left group and is stand alone?  - what other player has taken over coordination
- is still in group but another player has taken haver coordinator role
- ???

Tell me your use case and we should be able to find a solution.

**Comment by hklages** [comment]
timed out
