### ISSUE TITLE
Incorrect IP for listener

### ISSUE THREAD

**Issue by patrickharris** [hklages/node-red-contrib-sonos-events#3]
I'm using node-red within a docker container. I'm not receiving any events at all. When I create a listener node, the suggested default is 192.168.224.2 but I override this with the IP accessible within the LAN of 192.168.86.133. When I visit 192.168.86.133:6329/status it works, but displays "subscriptionUrl: http://192.168.224.2:6329/sonos/", so I'm assuming the default IP is not being overridden correctly.

Thanks for your work with Sonos and node-red!

**Comment by hklages** [comment]
What happens if you use the default? 

In your docker container: what ip addresses are available? (docker terminal, bash, ifconfig)

**Comment by patrickharris** [comment]
The default didn't work for me (and isn't accessible by the LAN), but is accessible from the computer hosting the docker container.
Link encap:Ethernet  HWaddr 02:42:C0:A8:E0:02  
          inet addr:192.168.224.2  Bcast:192.168.239.255  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:719 errors:0 dropped:0 overruns:0 frame:0
          TX packets:580 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:213384 (208.3 KiB)  TX bytes:4050749 (3.8 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:70 errors:0 dropped:0 overruns:0 frame:0
          TX packets:70 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:16436 (16.0 KiB)  TX bytes:16436 (16.0 KiB)

I really want it to use the computer's LAN IP, and of course in docker-compose I map port 6329.

**Comment by hklages** [comment]
So Docker Container has only one address: 192.168.224.2 - that means 192.168.86.133 can NOT be used. 

To what system belongs 192.168.86.133? 
Are you sure you get a status when calling `192.168.86.133:6329/status`?

Some background: 
sonos-events can be installed in a Docker container. As soon as you deploy an event node it will CREATE a small web server in that docker container using port 6329 and ip address. This ip address must be on of the container ip addresses  (looking at your ifconfig output: there is only 192.168.224.2 available).

It is NOT possible to choose any available IP address in your local network because we have to CREATE a WEBSERVER at that ip address. So if for instance 192.168.86.133 is a pc in your network sonos-event has no rights to create there a web server. 
If you install node-red + sonos-events on that pc you can use it. 

What ip addresses are allowed: 
In the config node you can use the search button. It will start a discovery to find all available addresses in your docker container. You have to use one of them and then you should receive the events. 
Sometimes the discovery does not work (port 1900 is blocked). In that case you will not see any ip address. So then you have to enter manually but even then it must be an ip address of that ifconfig of your docker container. 

Are you sure that using the default ip address (leave blank) does not output any data after deploying/restart flows?  It should work assuming discovery works and shows the valid ip address (thats done also internally when selecting the ip address)

**Comment by patrickharris** [comment]
The default IP chosen by the node is inside the container, and is not accessible from the LAN. That's why I want to use IP of the computer hosting the docker containers, and hence your server service.

**Comment by patrickharris** [comment]
![screenshot](https://user-images.githubusercontent.com/921942/113463377-daf34480-9481-11eb-91f2-57178be79a24.png)

**Comment by patrickharris** [comment]
As this similar sonos events service https://www.npmjs.com/package/sonos2mqtt/v/3.0.3 says about docker "but because you're running in docker it cannot figure out the IP by itself."

**Comment by hklages** [comment]
OK - regarding container my knowledge is limited. 

I did setup docker on a Synology NAS with option "using same network" as docker host. In that case discovery and subscription work and events come in. 

Did you setup the container with "own" network? Do you now have inside the docker container the address "192.168.224.2" and outsider on your pc the address "192.168.86.133"?  
How do you link both address? Does that work for all ports? 

I check with Stephan - he owns the sonos2mqtt and also sonos-ts (on this node-red-contrib-sonos-events is based)

**Comment by hklages** [comment]
I got the following information: [docker](https://svrooij.io/sonos2mqtt/getting-started.html#run-sonos2mqtt-in-docker)
You need to set env variable  `SONOS_LISTENER_HOST` and "expose" the listener port. 
Does that help?

**Comment by declanwoods** [comment]
Hey @hklages, I am also using your plugin inside a docker container inside kubernetes.

I think the issue here is that the listener port and IP aren't being applied to the Small webserver you talk about. For instance on mine I override my port to 30716, however the service continues to run on 6329, even after a restart.

**Comment by declanwoods** [comment]
![image](https://user-images.githubusercontent.com/5573570/113553042-ad48ff80-9629-11eb-8f43-fbf5e44e15bf.png)
![image](https://user-images.githubusercontent.com/5573570/113553064-b639d100-9629-11eb-85b1-bcd1b7d8b31b.png)

**Comment by patrickharris** [comment]
@hklages Thanks for your help - confirming that fixes the issue for me!

@declanwoods The docs for [sonos2mqtt](https://svrooij.io/sonos2mqtt/getting-started.html ) don't give an option for altering the port, and suggest that altering it will cause problems.

**Comment by hklages** [comment]
@patrickharris - perfect. What exactly did you do - only setting the env variable or more?

**Comment by patrickharris** [comment]
@hklages Just added `- SONOS_LISTENER_HOST=192.168.86.133 # Docker host IP` under `environment:` in my docker-compose file for the node-red service. I already had the port mapped, and it appears that can not be altered from 6329.

**Comment by declanwoods** [comment]
@patrickharris Thanks for that. What is the Listener port for then? Even so, it doesn't appear that my Listener IP setting is applying. 

Here is what I have at `/status` 
```
{"host":"10.244.0.167","port":6329,"isListening":true,"subscriptionUrl":"http://10.244.0.167:6329/sonos/{sonos-uuid}/{serviceName}"}
```

Omitted the rest, but the subscriptions are listed too. I'm not fully versed in this, but I assume that the `subscriptionUrl` is what is sent to the Sonos devices as the POST callback for events, right? The current address won't be valid for anything on my local network, hence I wanted to have it at http://192.168.0.171:30716. If this is won't work I will just add to nginx reverse proxy

**Comment by declanwoods** [comment]
Nevermind, I was able to just supply the `SONOS_LISTENER_HOST` and `SONOS_LISTENER_PORT` envs too! 😂

**Comment by patrickharris** [comment]
@declanwoods Ahh cool - so you can change the port? Okay, that's good news. I didn't realise there was a `SONOS_LISTENER_PORT`. The docs say "That is why you need to expose the listening port (6329), changing the port will cause problems.".

**Comment by hklages** [comment]
great - thanks for the feedback. Next release will include this information for "docker installations"

**Comment by hklages** [comment]
@declanwoods I just see that you are from Australia. Do you use Spotify? 
One of my open topics is to find out the Spotify Country Code for Australia. I know already Europe/US. 
If you use Spotify (and node-red-contrib-sonos-plus) I would be interetested in getting the mysonos.export.item output of a Spotify album.

**Comment by declanwoods** [comment]
@hklages Yes sure! Is this why I'm currently having issues adding Spotify URI's to group play?

x-rincon-cpcontainer:1004206cspotify%3aalbum%3a537M91OtVxaFAgF4HYcQKY?sid=12&amp;flags=8300&amp;sn=18

**Comment by hklages** [comment]
@declanwoods  Exactly! 
Please use the official Sonos app, go to the browse tab, select Apotify and choose an album. 
There is burger menu to add that to  your My Sonos tab. 
This album should then show up in your My Sonos tab under category Album. 

Then use the "My Sonos" node with mysonos.export.item and the title as payload. 
Send the output either by email to nrcsplus@gmail.com or attach it here as code.

**Comment by declanwoods** [comment]
I'll just paste here, this is the msg.payload. Does this mean its 3079?
```
{"uri":"x-rincon-cpcontainer:1004206cspotify%3aalbum%3a537M91OtVxaFAgF4HYcQKY?sid=12&amp;flags=8300&amp;sn=18","metadata":"&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;1004206cspotify%3aalbum%3a537M91OtVxaFAgF4HYcQKY&quot; parentID=&quot;10052064spotify%3aartist%3a6yrtCy4XJHXM6tczo4RlTs&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;14 Steps To A Better You&lt;/dc:title&gt;&lt;upnp:class&gt;object.container.album.musicAlbum&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON3079_X_#Svc3079-9518bba0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;","queue":true}
```

**Comment by hklages** [comment]
Opps. Yes that's region America. In your email you send me teh export for playlist with region Europe 2311. 
Did you swap between two regions/systems.

Here is a work around to play an album with region 3079:   #142
[issue 142 - the export](https://github.com/hklages/node-red-contrib-sonos-plus/issues/142)

**Comment by patrickharris** [comment]
Shit - I've just remembered, I think I changed my region in my Sonos
account a year or two ago to get their google and alexa services working
(as back then they were only available in the US and UK I think). I'm not
sure whether that has altered anything.

**Comment by hklages** [comment]
Ah - that's why there is a Europe region. 

Regarding TTS notification: [info](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/B.1-TTS-Notification)

**Comment by theverex** [comment]
@hklages do you still need an Australian Spotify Export? I'm trying to use the group.queue.urispotify node but it does not work with an error 800.

Your workaround from #142 works, but if you want an AU region to fix this then let me know.

**Comment by hklages** [comment]
Sure :-) 

Activate your Australien SPOTIFY account on the SONOS device, add a playlist to My Sonos, do the mysonos.export and send the outcome to my email address nrcsplus@gmail.com.

Cheers, Henning
