### ISSUE TITLE
How to listen on alarm clock event?

### ISSUE THREAD

**Issue by dprokscha** [hklages/node-red-contrib-sonos-events#4]
I need an event if the alarm clock of Sonos is triggered. So I configured the node to "AlarmClock raw" and/or "AlarmClock list version". Both creates an event if the alarm clock is triggered, but I also got events if I made changes to my alarms via the Sonos app. And I can't see a way to make a difference between an event like "alarm triggered" or "alarm changed", because msg.payload only gives me the name of the player like "RINCON_1234567890". Is this part still under development or am I just doing something completely wrong?

Thanks for your help!

**Comment by hklages** [comment]
SONOS provides only 1 AlarmClockService event: when the list has been changed. You then get the new list name. Thats all. Are you sure that there is an event when the alarm is triggered? 

You can use that trigger to request the full list and store it in a Node-RED global variable (persistant not memory) and create your own triggers for the Alarms.  I attach the flow to get the full list. 
Does that help? 

`[{"id":"73cc63d8.b1bcac","type":"sonosevents-selection","z":"ebb42d9b.e3e99","name":"","confignode":"fba01952.d104c8","playerHostname":"192.168.178.35","events":[{"fullName":"AlarmClockService.alarmListVersion"}],"outputs":1,"x":170,"y":700,"wires":[["f94bab3f.eb5898"]]},{"id":"5435d9af.214928","type":"sonos-universal","z":"ebb42d9b.e3e99","confignode":"f166c7c9.fa00c8","command":"message","state":"","stateType":"str","avoidCheckPlayerAvailability":false,"name":"","x":539,"y":700,"wires":[["7874c847.0a4ee8"]]},{"id":"9336fa5c.635468","type":"debug","z":"ebb42d9b.e3e99","name":" after xml","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1009,"y":700,"wires":[]},{"id":"f94bab3f.eb5898","type":"change","z":"ebb42d9b.e3e99","name":"get alarm list","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"endpoint\":\"/AlarmClock/Control\",\"action\":\"ListAlarms\",\"inArgs\":{}}","tot":"json"},{"t":"set","p":"topic","pt":"msg","to":"player.test","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":377,"y":700,"wires":[["5435d9af.214928"]]},{"id":"6e6387a1.d3c9c8","type":"xml","z":"ebb42d9b.e3e99","name":"","property":"payload","attr":"tagAtt","chr":"","x":859,"y":700,"wires":[["9336fa5c.635468"]]},{"id":"7874c847.0a4ee8","type":"change","z":"ebb42d9b.e3e99","name":"only alarms","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.CurrentAlarmList","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":709,"y":700,"wires":[["6e6387a1.d3c9c8"]]},{"id":"1dce8629.fb58aa","type":"comment","z":"ebb42d9b.e3e99","name":"Modify","info":"Please modify config and use your ip address","x":550,"y":673,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"1f9bafad.9580c","type":"comment","z":"ebb42d9b.e3e99","name":"Modify","info":"use your ip address","x":220,"y":671,"wires":[],"icon":"font-awesome/fa-arrow-down"},{"id":"fba01952.d104c8","type":"sonosevents-config","name":"household","listenerHostname":"","listenerPort":""},{"id":"f166c7c9.fa00c8","type":"sonos-config","name":"yourplayer","serialnum":"","ipaddress":"192.168.178.35"}]`

**Comment by dprokscha** [comment]
Thanks for your fast reply! Currently I am trying to replace OpenHAB with Node-RED only. OpenHAB has an event trigger for alarms from Sonos. But after your explanation I guess OpenHAB just reads the list of alarms and makes this event trigger by itself. So I will do the same in Node-RED. But for this I need some more help to receive the list of alarms. Because your example above throws an error `player.test: statusCode 500 & upnpErrorCode 714. upnpErrorMessage >>unknown error :: Details: none` for the universal node. I fired your example against the coordinator of my group and against a single player for which the alarms are configured. I also dug through the Wiki to find more informations for the command "player.test" or how to send this kind of URI-commands to the universal node, but had no luck to get it to work. Could you please give me some further information about this?

**Comment by hklages** [comment]
What sonos-plus version is installed. That example only works with 5.0.5 or higher

**Comment by dprokscha** [comment]
Updated from 5.0.4 to 5.0.6 and now it works. Thanks! 👍 

If you have some time: Could you please explain what "player.test" ist doing and how to use it?

**Comment by hklages** [comment]
The "player.test" is a very special command. You can send any available SONOS action with it (one restriction:  you need to copy before the CONTENT from Db-ActionsV6All.json to Db-ActionsV6.json - otherwise only a selection of actions is available). It is located in directory "src" and it is the "knowledge base". Here is the documentation of the [SONOS actions](https://svrooij.io/sonos-api-docs/). 

In your case: Dont care about it.  It was only to help you out with the missing "get.alarms" command, what is not yet implemented. In one of the next releases there will be an alarm command. Thats still missing.

**Comment by hklages** [comment]
Moving from OpenHAB to Node-RED can be a lot of work - depending how many devices you own and what you expect from a user interface. Since a few weeks I use Home Assistant together with NodeRED. That has already a lot build in and the missing parts I do in Node-RED

**Comment by dprokscha** [comment]
Yes, I know. I am using OpenHAB for ages and with Node-RED as a replacement for the rule engine. In the last year I simplified my setup to only using devices from Philips hue, Sonos and a Xaoimi Vacuum. And I realized, that most stuff is completely automated or triggered by physical switches to turn devices/scenes on/off. There are only some cases where I need an UI - and for this I will use virtual devices for Apple Homekit. It seems all my needs are covered by Node-RED. A really cool side-effect is much less effort to configure and to maintain all the things and a very fast reaction of the devices, because I can omit the hop through OpenHAB and I am able to communicate to the devices directly through Node-RED. But yes, if you have a lots of devices from different manufactures which communicates through lots of protocols, then systems like HA or OpenHAB are the way to be 😉 

Could you please close this issue as far you have implemented the "get.alarms" command? Would be easier for me to follow your changes and to update my flows.

**Comment by hklages** [comment]
Try 5.1.0 - there is an alarm list and also enable/disable alarm.

I close this issue. Please open a new one if there are still issues.

**Comment by dprokscha** [comment]
Just to leave a virtual beer: Works perfectly! Thanks a lot! 🍻

**Comment by hklages** [comment]
Thanks for the feedback :-)
