### ISSUE TITLE
Events can't be selected

### ISSUE THREAD

**Issue by Blomus** [hklages/node-red-contrib-sonos-events#7]
Unfortunately, I can no longer select "Events - order defines outputs" although the node seems to be correctly connected to Port 6329.
Can this problem be related to the update to the Sonos S2 app?
Do you have any other ideas how this problem can be solved?

Kind regards

**Comment by hklages** [comment]
Hi. I develop and test the node with SONOS S2 installed on all devices. So that should not be the problem. 

What version do you use: 
- nodeRED, nodeJS, 
- sonos-event

What browser? 
Did you try another browser? Delete the cache?

**Comment by Blomus** [comment]
Hi, 
- nodeRed v1.3.1
- nodeJS v12.22.1
- sonos-event 1.0.0

I use Firefox and Safari. I also deleted the cache, unfortunately without success

**Comment by hklages** [comment]
Current NodeRED version is 2.x but sonos-events should work with. 1.3.1

Are you able to update sonos-events to 1.0.2. That's the current version. Afterwards you have to again delete the cache 
and please try to add a new sonos-plus node.

**Comment by Blomus** [comment]
Updating to sonos-events 1.0.2 was also unsuccessful.
Sonos-plus nodes work without problems.
What I noticed is that no matter which port is configured, a connection to port 6329 is displayed.
Is that plausible for you?
Would an update do NodeRed version 2.x solve my problem?

Kind regards.

**Comment by hklages** [comment]
Thats strange. sonos-events reuses a loto f sonos-plus. Maybe there is a problem with the ports. Are the ports for discovery open: 1900 and 6329?

Can you send a screen shot of the config node and the node? (drag it into this window with open reply window)
Do the search buttons in the config node provide ip addresses and the search button in the node field your sonos player? 

What environment do you use? Docker? Raspberry Pi? Windows?

**Comment by hklages** [comment]
timed out
