### ISSUE TITLE
Possible to add changing power source / battery level of Sonos Move/Roam as an event?

### ISSUE THREAD

**Issue by mac89muc** [hklages/node-red-contrib-sonos-events#8]
Hello,

I've posted the question additionally at the node-red-contrib-sonos-plus git page [here](https://github.com/hklages/node-red-contrib-sonos-plus/issues/200)
Is it possible to add the power source of the Sonos Move/Roam and the Batterylevel as an event?
Would be nice to integrate into a flow if the Move/Roam is not USB powered and is playing music battery powered.

The power source is provided e.g. via web request http://192.168.178.125:1400/status/batterystatus

![image](https://user-images.githubusercontent.com/69312437/152116864-cca7b79f-6eca-40e5-81c3-77ef6e756398.png)

![image](https://user-images.githubusercontent.com/69312437/152116876-ec7909fd-97ad-4e56-be3a-25b734fe3d2d.png)

![image](https://user-images.githubusercontent.com/69312437/152116895-355e6627-8ce1-4d15-afef-353342628024.png)

Regards

**Comment by hklages** [comment]
Hi. 
I could not find any SONOS event related to battery. Let me check.

**Comment by hklages** [comment]
I bought a SONO Roam and checked the state list. There is no data for battery in the SOAP model / event model. 

The only thing you can do is to poll the state every hour (player.get.batterylevel or do the plain  http://192.168.178.125:1400/status/batterystatus.
